sonar.projectKey=oraculo
sonar.projectName=Oraculo
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8


sonar.modules=backend,frontend


backend.sonar.projectBaseDir=backend
backend.sonar.projectName=Backend
backend.sonar.sources=src
backend.sonar.tests=src
backend.sonar.test.inclusions=**/*.spec.ts
backend.sonar.javascript.lcov.reportPaths=coverage/lcov.info
backend.sonar.exclusions=**/*.spec.ts
backend.sonar.coverage.exclusions=**


frontend.sonar.projectBaseDir=frontend
frontend.sonar.projectName=Frontend
frontend.sonar.sources=.
frontend.sonar.exclusions=node_modules/**, .next/**, dist/**, out/**, coverage/**
