# Usa uma imagem base leve e compatível
FROM node:22-slim

# Diretório de trabalho
WORKDIR /app

# Copia dependências
COPY package.json ./
COPY yarn.lock ./

# Instala dependências do sistema necessárias
RUN apt-get update && apt-get install -y \
    git \
    python3 \
    make \
    g++ \
    libc6-dev \
    && rm -rf /var/lib/apt/lists/*

# Instala as dependências do projeto
RUN yarn install --frozen-lockfile

# Copia o restante do código
COPY . .

# Build do projeto para produção
RUN yarn build

# Define ambiente (será sobrescrito em docker-compose ou Railway)
ENV NODE_ENV=development

# Expõe as portas
EXPOSE 21165

# Inicia a aplicação
CMD ["yarn", "start"]
